services:
  app-prod:
    build:
      context: .
      args:
        - NODE_ENV=production
    ports:
      - '5002:5002'

  app-dev:
    build:
      context: .
      target: deps
    command: npm run dev
    ports:
      - '5002:5002'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
